# Setup
title: vigil2
description: Dev Log
url: https://vigil2.github.io
avatar: /assets/vigil_icon.png
paginate: 5
permalink: pretty
cover_image: /assets/kindred.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: vigil2
  card: summary
logo: logo.png
social:
  name: vigil2
  links:
    # - https://twitter.com/vigil2
    - https://github.com/vigil2
google_site_verification: i_YYjfSn-7CNjUxxWWRM3lb50toQt6rY1vesEf_jmkI
lang: ko

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: G-8C0WFCTWT3

# Replace this value and uncomment to enable Disqus
disqus: 
  shortname: vigil2_blog

# Specify the author for blog posts
author:
  name: vigil2
  url: https://github.com/vigil2/
  email: l2nak87@gmail.com
